[book]
authors = ["Amir Zeldes", "Florian Zipser", "Arne Neumnann", "Thomas Krause"]
language = "en"
multilingual = false
src = "src"
title = "PAULA XML Documentation"

[output.html]
mathjax-support = true

[output.latex]
latex = true
pdf = true